---
iosv-1:
    hostname: '192.168.2.71'
    port: 22
    username: 'cisco'
    password: 'cisco'
    platform: 'cisco_ios'

iosv-2:
    hostname: '192.168.2.72'
    port: 22
    username: 'cisco'
    password: 'cisco'
    platform: 'cisco_ios'
